
export const fontOptions = [
  { value: "default", label: "System Default", family: "-apple-system, BlinkMacSystemFont, system-ui" },
  { value: "poppins", label: "Poppins", family: "'Poppins', sans-serif" },
  { value: "montserrat", label: "Montserrat", family: "'Montserrat', sans-serif" },
  { value: "raleway", label: "Raleway", family: "'Raleway', sans-serif" },
  { value: "source-sans", label: "Source Sans 3", family: "'Source Sans 3', sans-serif" },
  { value: "nunito", label: "Nunito", family: "'Nunito', sans-serif" },
  { value: "quicksand", label: "Quicksand", family: "'Quicksand', sans-serif" },
  { value: "mulish", label: "Mulish", family: "'Mulish', sans-serif" },
  { value: "work-sans", label: "Work Sans", family: "'Work Sans', sans-serif" },
  { value: "dm-sans", label: "DM Sans", family: "'DM Sans', sans-serif" },
  { value: "rubik", label: "Rubik", family: "'Rubik', sans-serif" },
  { value: "lato", label: "Lato", family: "'Lato', sans-serif" },
  { value: "merriweather", label: "Merriweather", family: "'Merriweather', serif" },
  { value: "source-serif", label: "Source Serif 4", family: "'Source Serif 4', serif" },
  { value: "crimson-pro", label: "Crimson Pro", family: "'Crimson Pro', serif" },
  { value: "libre-baskerville", label: "Libre Baskerville", family: "'Libre Baskerville', serif" },
  { value: "spectral", label: "Spectral", family: "'Spectral', serif" },
  { value: "archivo", label: "Archivo", family: "'Archivo', sans-serif" },
  { value: "space-grotesk", label: "Space Grotesk", family: "'Space Grotesk', sans-serif" },
  { value: "ibm-plex-sans", label: "IBM Plex Sans", family: "'IBM Plex Sans', sans-serif" },
  { value: "ibm-plex-serif", label: "IBM Plex Serif", family: "'IBM Plex Serif', serif" },
  { value: "bitter", label: "Bitter", family: "'Bitter', serif" },
  { value: "pt-serif", label: "PT Serif", family: "'PT Serif', serif" },
  { value: "pt-sans", label: "PT Sans", family: "'PT Sans', sans-serif" },
];
